name: Daily Commit

on:
  schedule:
    - cron: '0 7 * * *'  # Runs every day at 7 AM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Make Dummy Commit
        run: |
          date >> log.txt
          git config user.name "sianyinguno"
          git config user.email "sianyinguno@gmail.com"
          git add log.txt
          git commit -m "Daily log update"
          git push
